import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://dponbrmfxbqeqrlqqzei.supabase.co';
// Usando a chave fornecida pelo usuário
const supabaseKey = 'sb_publishable_GV2iv34TeDLz5vEhpP1UiQ_Pr7mAvQp';

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
  REQUISITOS DO BANCO DE DADOS (SQL):
  
  Para que o App funcione perfeitamente, execute o seguinte SQL no painel do Supabase (SQL Editor).
  Isso cria a tabela e permite acesso público (já que é um app de demonstração sem login real).

  -- 1. Criação da tabela
  create table if not exists messages (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    session_id text not null,
    text text,
    sender text not null,
    image text,
    audio text,
    mime_type text,
    status text default 'sent'
  );

  -- 2. Configuração de segurança (RLS)
  -- Para este demo funcionar sem Auth, precisamos desabilitar o RLS ou criar uma policy publica.
  -- Opção mais simples para demo:
  alter table messages enable row level security;

  create policy "Public Access"
  on messages
  for all
  using (true)
  with check (true);
*/